name: Deploy Sanity CMS

on:
  push:
    branches:
      - main
    paths:
      - 'nine-mile-store-cms/**'
  workflow_dispatch:  # Allow manual triggering

jobs:
  deploy-sanity:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./nine-mile-store-cms
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './nine-mile-store-cms/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Deploy Sanity Studio
        run: npx sanity deploy --no-verify
        env:
          SANITY_AUTH_TOKEN: ${{ secrets.SANITY_DEPLOY_TOKEN }} 